"""update scene to contain 'is_pre_final'

Revision ID: 3580072425da
Revises:
Create Date: 2025-06-19 18:38:10.322716

"""

import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "3580072425da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("choice", sa.Column("is_pre_final", sa.Boolean(), nullable=True))
    op.drop_column("story", "choices_weights")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story", sa.Column("choices_weights", sqlite.JSON(), nullable=True))
    op.drop_column("choice", "is_pre_final")
    # ### end Alembic commands ###
